version: "3"

services:
  golang-bvhtoolbox:
    build: .
    ports:
      - "2025:22"
    user: $DOCKER_USER:$DOCKER_GROUP
    volumes:
      - './:/home/Hosting/workspace:rw'
      - '~/.ssh:/home/Hosting/.ssh:ro'
      - '~/.gitconfig:/home/Hosting/.gitconfig:ro'